// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package dense

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DenseFloat32 struct {
	_tab flatbuffers.Table
}

func GetRootAsDenseFloat32(buf []byte, offset flatbuffers.UOffsetT) *DenseFloat32 {
	_ = "STUB: not implemented"
	return nil
}

func FinishDenseFloat32Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	_ = "STUB: not implemented"
	return
}

func GetSizePrefixedRootAsDenseFloat32(buf []byte, offset flatbuffers.UOffsetT) *DenseFloat32 {
	_ = "STUB: not implemented"
	return nil
}

func FinishSizePrefixedDenseFloat32Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	_ = "STUB: not implemented"
	return
}

func (rcv *DenseFloat32) Init(buf []byte, i flatbuffers.UOffsetT) {
	_ = "STUB: not implemented"
	return
}

func (rcv *DenseFloat32) Table() flatbuffers.Table {
	_ = "STUB: not implemented"
	return *new(flatbuffers.Table)
}

func (rcv *DenseFloat32) Dtype() int32 { _ = "STUB: not implemented"; return 0 }

func (rcv *DenseFloat32) MutateDtype(n int32) bool { _ = "STUB: not implemented"; return false }

func (rcv *DenseFloat32) RequiresFrad() bool { _ = "STUB: not implemented"; return false }

func (rcv *DenseFloat32) MutateRequiresFrad(n bool) bool { _ = "STUB: not implemented"; return false }

func (rcv *DenseFloat32) Shape(j int) int32 { _ = "STUB: not implemented"; return 0 }

func (rcv *DenseFloat32) ShapeLength() int { _ = "STUB: not implemented"; return 0 }

func (rcv *DenseFloat32) MutateShape(j int, n int32) bool { _ = "STUB: not implemented"; return false }

func (rcv *DenseFloat32) Data(j int) float32 { _ = "STUB: not implemented"; return 0 }

func (rcv *DenseFloat32) DataLength() int { _ = "STUB: not implemented"; return 0 }

func (rcv *DenseFloat32) MutateData(j int, n float32) bool { _ = "STUB: not implemented"; return false }

func DenseFloat32Start(builder *flatbuffers.Builder) { _ = "STUB: not implemented"; return }

func DenseFloat32AddDtype(builder *flatbuffers.Builder, dtype int32) {
	_ = "STUB: not implemented"
	return
}

func DenseFloat32AddRequiresFrad(builder *flatbuffers.Builder, requiresFrad bool) {
	_ = "STUB: not implemented"
	return
}

func DenseFloat32AddShape(builder *flatbuffers.Builder, shape flatbuffers.UOffsetT) {
	_ = "STUB: not implemented"
	return
}

func DenseFloat32StartShapeVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	_ = "STUB: not implemented"
	return *new(flatbuffers.UOffsetT)
}

func DenseFloat32AddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	_ = "STUB: not implemented"
	return
}

func DenseFloat32StartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	_ = "STUB: not implemented"
	return *new(flatbuffers.UOffsetT)
}

func DenseFloat32End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	_ = "STUB: not implemented"
	return *new(flatbuffers.UOffsetT)
}
