// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package dense

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DenseFloat64 struct {
	_tab flatbuffers.Table
}

func GetRootAsDenseFloat64(buf []byte, offset flatbuffers.UOffsetT) *DenseFloat64 {
	_ = "STUB: not implemented"
	return nil
}

func FinishDenseFloat64Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	_ = "STUB: not implemented"
	return
}

func GetSizePrefixedRootAsDenseFloat64(buf []byte, offset flatbuffers.UOffsetT) *DenseFloat64 {
	_ = "STUB: not implemented"
	return nil
}

func FinishSizePrefixedDenseFloat64Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	_ = "STUB: not implemented"
	return
}

func (rcv *DenseFloat64) Init(buf []byte, i flatbuffers.UOffsetT) {
	_ = "STUB: not implemented"
	return
}

func (rcv *DenseFloat64) Table() flatbuffers.Table {
	_ = "STUB: not implemented"
	return *new(flatbuffers.Table)
}

func (rcv *DenseFloat64) Dtype() int32 { _ = "STUB: not implemented"; return 0 }

func (rcv *DenseFloat64) MutateDtype(n int32) bool { _ = "STUB: not implemented"; return false }

func (rcv *DenseFloat64) RequiresGrad() bool { _ = "STUB: not implemented"; return false }

func (rcv *DenseFloat64) MutateRequiresGrad(n bool) bool { _ = "STUB: not implemented"; return false }

func (rcv *DenseFloat64) Shape(j int) int32 { _ = "STUB: not implemented"; return 0 }

func (rcv *DenseFloat64) ShapeLength() int { _ = "STUB: not implemented"; return 0 }

func (rcv *DenseFloat64) MutateShape(j int, n int32) bool { _ = "STUB: not implemented"; return false }

func (rcv *DenseFloat64) Data(j int) float64 { _ = "STUB: not implemented"; return 0 }

func (rcv *DenseFloat64) DataLength() int { _ = "STUB: not implemented"; return 0 }

func (rcv *DenseFloat64) MutateData(j int, n float64) bool { _ = "STUB: not implemented"; return false }

func DenseFloat64Start(builder *flatbuffers.Builder) { _ = "STUB: not implemented"; return }

func DenseFloat64AddDtype(builder *flatbuffers.Builder, dtype int32) {
	_ = "STUB: not implemented"
	return
}

func DenseFloat64AddRequiresGrad(builder *flatbuffers.Builder, requiresGrad bool) {
	_ = "STUB: not implemented"
	return
}

func DenseFloat64AddShape(builder *flatbuffers.Builder, shape flatbuffers.UOffsetT) {
	_ = "STUB: not implemented"
	return
}

func DenseFloat64StartShapeVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	_ = "STUB: not implemented"
	return *new(flatbuffers.UOffsetT)
}

func DenseFloat64AddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	_ = "STUB: not implemented"
	return
}

func DenseFloat64StartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	_ = "STUB: not implemented"
	return *new(flatbuffers.UOffsetT)
}

func DenseFloat64End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	_ = "STUB: not implemented"
	return *new(flatbuffers.UOffsetT)
}
